# Generated by Django 3.0 on 2025-01-28 14:51

from django.db import migrations


def copy_data_to_new_tables(apps, schema_editor):
    # Load olds modals
    old_profiles = apps.get_model('oc_lettings_site', 'Profile')

    # Load news modals
    Profile = apps.get_model('profiles', 'Profile')

    # Copy data for Address
    for old_profile in old_profiles.objects.all():
        Profile.objects.create(
            id=old_profile.id,
            user=old_profile.user,
            favorite_city=old_profile.favorite_city,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_data_to_new_tables),
    ]
