name: Build and Push Docker Image

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/my-python-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}


      - name: Verify image locally (optional)
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }}
          docker run --rm -d -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }}
